# Binary classifier configuration for Waldo appearance learning
_target_: waldo_finder.binary_classifier.WaldoClassifier

# Model architecture
num_heads: 8
num_layers: 6  # Reduced for simpler task
hidden_dim: 256  # Smaller for appearance learning
mlp_dim: 1024
dropout_rate: 0.2
attention_dropout_rate: 0.2

# Input configuration
image_size: ${data.image_size}  # Inherit from data config
