# Vision Transformer configuration with advanced regularization techniques
model:
  # Hierarchical architecture with improved capacity control
  num_heads: 8
  num_layers: 8
  hidden_dim: 512
  mlp_dim: 2048
  
  # Advanced regularization suite
  dropout_rate: 0.3  # Increased for better regularization
  attention_dropout: 0.2  # Separate attention dropout
  path_dropout: 0.2  # Enhanced path dropout
  
  # Modern training stabilizers
  weight_decay: 0.2  # Increased for better regularization
  warmup_steps: 200  # Extended warmup
  max_grad_norm: 0.5  # Reduced for stability
  gradient_checkpointing: false  # Kept disabled for CPU
  
  # Advanced regularization techniques
  label_smoothing: 0.15
  mixup_alpha: 0.4  # Increased mixup
  cutmix_alpha: 0.4  # Increased cutmix
  drop_path_rate: 0.2
  stochastic_depth_rate: 0.2
  
  # Optimizer with modern techniques
  optimizer:
    type: adamw
    beta1: 0.9
    beta2: 0.999
    epsilon: 1.0e-8
    weight_decay_schedule: cosine  # Cosine decay for weight decay
    
  # Sophisticated learning rate schedule
  lr_schedule:
    type: cosine_with_restarts
    warmup_steps: 200
    decay_steps: 10000
    min_lr_ratio: 0.05
    cycles: 3  # Multiple cycles for better exploration
    restart_multiplier: 0.8  # Decay maximum lr after each restart
    
  # State-of-the-art augmentation pipeline
  augmentation:
    random_flip: true
    random_rotation: 45  # Increased rotation diversity
    random_scale: [0.7, 1.3]  # Wider scale range
    random_shear: 15
    color_jitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.25
    random_erasing: 0.25
    auto_augment: true
    trivial_augment: true
    random_augment:
      num_ops: 3
      magnitude: 15
    
    # Advanced augmentation techniques
    gridmask:  # GridMask augmentation
      ratio: 0.4
      rotate: 45
      invert: true
    
    mixup_cutmix:  # Enhanced mixing strategies
      mixup_prob: 0.7
      cutmix_prob: 0.7
      switch_prob: 0.3
      label_smoothing: 0.15
    
    random_resize_crop:  # More aggressive crop augmentation
      scale: [0.6, 1.0]
      ratio: [0.75, 1.33]
      
    # Consistency regularization
    consistency:
      enabled: true
      temperature: 0.07
      num_crops: 2
      weight: 0.5
