defaults:
  - _self_
  - model: binary_classifier
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

# Stage 1: Waldo Appearance Learning
experiment_name: waldo-finder-stage1

# Data configuration
data:
  train_dir: "${hydra:runtime.cwd}/training_data/stage1"  # Contains waldo/ and negative/ dirs
  val_split: 0.2  # 20% validation
  image_size: [128, 128]  # Smaller size for cropped images
  normalize: true
  cache_data: true
  augment: true

# Training configuration
training:
  seed: 42  # For reproducibility
  model_dir: "trained_model/stage1"  # Where to save model checkpoints
  batch_size: 16  # Larger batches for smaller images
  num_epochs: 50
  learning_rate: 0.0001
  warmup_epochs: 5
  
  # Training strategy
  gradient_accumulation_steps: 2
  mixed_precision: false  # CPU compatibility
  gradient_checkpointing: false
  ema: true
  ema_decay: 0.999
  
  # Early stopping
  eval_freq: 1
  save_best_only: true
  early_stopping:
    patience: 10
    min_delta: 0.001
    restore_best_weights: true
  
  # Augmentation settings
  augmentation:
    random_flip: true
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
    random_rotation: 10  # ±10 degrees
    random_scale: [0.9, 1.1]
  
  # Binary classification focus
  classification:
    positive_class_weight: 10.0  # Higher weight for rare Waldo class
    confidence_threshold: 0.8
    focal_loss:
      alpha: 0.75
      gamma: 2.0

# Model configuration overrides
model:
  num_heads: 8
  num_layers: 6  # Reduced for simpler task
  hidden_dim: 256  # Smaller for appearance learning
  mlp_dim: 1024
  dropout_rate: 0.2
  attention_dropout_rate: 0.2

# Hydra settings
hydra:
  run:
    dir: outputs/stage1/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True
