defaults:
  - _self_
  - model: vit_base_optimized  # Use our optimized model config
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

# Experiment settings
experiment_name: waldo-finder-jax-optimized
seed: 42

# Data settings
data:
  train_dir: "."
  val_dir: "."
  image_size: [640, 640]
  num_workers: 4
  prefetch_factor: 2

# Advanced training settings
training:
  batch_size: 4  # Increased for better batch statistics
  num_epochs: 100  # Extended for cyclic learning rate
  steps_per_epoch: null
  learning_rate: 0.0005  # Reduced for stability
  seed: ${seed}
  model_dir: ${hydra:runtime.output_dir}/models
  
  # Advanced training features
  gradient_accumulation_steps: 8  # Increased for larger effective batch
  mixed_precision: false  # Kept disabled for CPU
  gradient_checkpointing: false  # Kept disabled for CPU
  
  # Enhanced EMA settings
  ema: true
  ema_decay: 0.9998  # Increased for better stability
  ema_update_every: 10  # Update less frequently
  
  # Advanced evaluation settings
  eval_freq: 1
  save_best_only: true
  metric_for_best_model: "val_loss"
  greater_is_better: false
  
  # Sophisticated early stopping
  early_stopping:
    patience: 10  # Increased for cyclic lr
    min_delta: 0.0005  # More sensitive
    mode: "min"
    baseline: null
    restore_best_weights: true
    
  # Advanced monitoring
  monitoring:
    log_every_n_steps: 50
    eval_every_n_steps: 200
    save_every_n_steps: 500
    
  # Enhanced loss weighting for center-size prediction
  loss_weights:
    bbox_loss: 1.0
    giou_loss: 2.0  # Keep high weight for IoU
    confidence_loss: 0.5
    size_loss: 1.0  # New loss for box size constraints
    center_loss: 1.5  # New loss for center prediction
    
  # Box prediction constraints
  box_constraints:
    min_size: 0.1  # Minimum box dimension
    max_size: 0.4  # Maximum box dimension
    size_target: 0.15  # Target box size for penalty
    size_penalty: 5.0  # Strength of size penalty
    
  # Advanced regularization
  regularization:
    gradient_clip_norm: 0.5
    weight_decay: 0.2
    label_smoothing: 0.15
    consistency_weight: 0.5  # Weight for consistency loss
    
  # Warmup settings
  warmup_epochs: 5  # Moved to top level for compatibility
  
  # Learning rate schedule
  lr_schedule:
    min_lr: 1e-6
    cycle_momentum: true
    cycle_decay: 0.8
    
  # Enhanced validation settings
  validation:
    eval_steps: 100  # Evaluate on subset for faster feedback
    save_predictions: true
    confidence_threshold: 0.5
    min_box_size: 0.1  # Minimum valid box size
    max_box_size: 0.4  # Maximum valid box size
    iou_threshold: 0.5  # IoU threshold for matches

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True
