defaults:
  - _self_
  - model: vit_base
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# Experiment settings
experiment_name: waldo-finder-jax
seed: 42

# Data settings
data:
  train_dir: ${oc.env:DATA_DIR}/train
  val_dir: ${oc.env:DATA_DIR}/val
  image_size: [640, 640]

# Training settings
training:
  batch_size: 16
  num_epochs: 100
  steps_per_epoch: 100
  learning_rate: 0.0001
  seed: ${seed}
  model_dir: ${hydra:runtime.output_dir}/models

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True
