defaults:
  - _self_
  - model: vit_base_optimized
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

# Experiment settings
experiment_name: waldo-finder-jax-optimized-v2
seed: 42

# Data settings
data:
  train_dir: "."
  val_dir: "."
  image_size: [640, 640]

# Advanced training settings
training:
  batch_size: 4
  num_epochs: 100
  steps_per_epoch: null
  learning_rate: 0.0003  # Slightly increased now that we have stability
  seed: ${seed}
  model_dir: ${hydra:runtime.output_dir}/models
  
  # Advanced training features
  gradient_accumulation_steps: 8
  mixed_precision: false
  gradient_checkpointing: false
  
  # Enhanced EMA settings
  ema: true
  ema_decay: 0.9995  # Slightly reduced for faster adaptation
  ema_update_every: 5  # More frequent updates
  
  # Advanced evaluation settings
  eval_freq: 1
  save_best_only: true
  metric_for_best_model: "val_loss"
  greater_is_better: false
  
  # Sophisticated early stopping
  early_stopping:
    patience: 15  # Increased for new lr schedule
    min_delta: 0.0001  # More sensitive
    mode: "min"
    baseline: null
    restore_best_weights: true
    
  # Advanced monitoring
  monitoring:
    log_every_n_steps: 50
    eval_every_n_steps: 200
    save_every_n_steps: 500
    
  # Loss weighting
  loss_weights:
    bbox_loss: 1.0
    giou_loss: 1.0  # Reduced to balance with other losses
    confidence_loss: 0.5
    
  # Advanced regularization
  regularization:
    gradient_clip_norm: 0.5  # Reduced for better stability
    weight_decay: 0.01  # Further reduced
    label_smoothing: 0.1
    consistency_weight: 0.001  # Further reduced since it's dominating
    
  # Warmup settings
  warmup_epochs: 5  # Increased warmup for better initialization
  
  # Learning rate schedule
  lr_schedule:
    min_lr: 1e-5  # Increased min lr
    cycle_momentum: true
    cycle_decay: 0.85  # Gentler decay
    num_cycles: 5  # Explicit number of cycles
    
  # Validation settings
  validation:
    eval_steps: 100
    save_predictions: true
    confidence_threshold: 0.5

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True
