defaults:
  - _self_
  - model: vit_base
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

# Waldo-focused configuration
experiment_name: waldo-finder-scale-aware
seed: 42  # For reproducibility

# Data pipeline configuration
data:
  train_dir: "."
  val_dir: "."
  image_size: [640, 640]  # Maintain resolution for pattern details
  normalize: true
  cache_data: true
  scale_aware: true  # Enable scale-aware processing

# Training configuration optimized for precise localization
training:
  batch_size: 4  # Increased for better statistics
  num_epochs: 150  # Extended for augmented data
  steps_per_epoch: null
  learning_rate: 0.00003  # Further reduced for augmented data
  seed: ${seed}
  model_dir: ${hydra:runtime.output_dir}/models
  warmup_epochs: 12  # Extended warmup for augmented data
  
  # Optimized training strategy
  gradient_accumulation_steps: 4  # Adjusted for new batch size
  mixed_precision: false  # CPU compatibility
  gradient_checkpointing: false  # CPU compatibility
  ema: true
  ema_decay: 0.9999  # Increased for augmented data stability
  
  # Tightened evaluation strategy
  eval_freq: 1
  save_best_only: true
  early_stopping:
    patience: 30  # Extended for augmented data
    min_delta: 0.0001  # More strict improvement threshold
    restore_best_weights: true
    
  # Core features
  sync_bn: true
  find_unused_parameters: true
  
  # Rebalanced loss weights for better localization
  loss_weights:
    giou: 8.0  # Heavily weighted for precise boxes
    l1: 4.0    # Increased for better coordinate accuracy
    confidence: 0.1  # Reduced to prevent overconfidence
    size: 2.0  # Stronger size constraints
  
  # Enhanced metrics for better convergence
  metrics:
    iou_threshold: 0.5  # Base IoU threshold
    confidence_threshold: 0.9  # Maintain high confidence
    size_range: [0.05, 0.15]  # More restrictive size range
    scale_bins: [0.05, 0.075, 0.1, 0.125, 0.15]  # Focused scale bins
    
  # Scale-aware training features
  scale_aware:
    enabled: true
    size_weights: [3.0, 2.0, 1.0, 2.0, 3.0]  # Higher penalty for extreme sizes
    adaptive_loss: true
    size_normalization: true

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True
