defaults:
  - _self_
  - model: vit_base
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

# Experiment settings
experiment_name: waldo-finder-jax
seed: 42

# Data settings
data:
  train_dir: "."  # Default to current directory, can be overridden via command line
  val_dir: "."    # Use same directory for validation during development
  image_size: [640, 640]

# Advanced training settings
training:
  batch_size: 8  # Reduced batch size for better memory efficiency
  num_epochs: 200  # Extended training for better convergence
  steps_per_epoch: null  # Dynamic steps based on dataset
  learning_rate: 0.0001  # Increased learning rate for Lion optimizer
  seed: ${seed}
  model_dir: ${hydra:runtime.output_dir}/models
  warmup_epochs: 5  # Optimized warmup period
  
  # Advanced training features
  gradient_accumulation_steps: 8  # Increased for effective batch size of 64
  mixed_precision: true  # Use mixed precision training
  gradient_checkpointing: true  # Save memory
  ema: true  # Use exponential moving average of weights
  ema_decay: 0.9999
  
  # Advanced evaluation
  eval_freq: 1  # Evaluate every epoch
  save_best_only: true
  early_stopping:
    patience: 20
    min_delta: 0.0001
    
  # Multi-GPU training settings
  sync_bn: true  # Sync batch norm stats across GPUs
  find_unused_parameters: true

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True
