defaults:
  - _self_
  - model: vit_base
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

# Experiment settings
experiment_name: waldo-finder-jax
seed: 42

# Data settings
data:
  train_dir: "."  # Default to current directory, can be overridden via command line
  val_dir: "."    # Use same directory for validation during development
  image_size: [640, 640]

# Advanced training settings
training:
  batch_size: 2  # Smaller batch size for more frequent updates
  num_epochs: 50  # Reduced epochs since we have small dataset
  steps_per_epoch: null  # Dynamic steps based on dataset
  learning_rate: 0.001  # Increased learning rate for better optimization
  seed: ${seed}
  model_dir: ${hydra:runtime.output_dir}/models
  warmup_epochs: 3  # Shorter warmup for small dataset
  
  # Advanced training features
  gradient_accumulation_steps: 4  # Reduced accumulation for more frequent updates
  mixed_precision: false  # Disabled for CPU training
  gradient_checkpointing: false  # Disabled for CPU training
  ema: true  # Use exponential moving average of weights
  ema_decay: 0.9995  # Adjusted for better stability
  
  # Advanced evaluation
  eval_freq: 1  # Evaluate every epoch
  save_best_only: true
  early_stopping:
    patience: 5  # Reduced patience since we expect faster convergence
    min_delta: 0.001  # Increased min delta to avoid overfitting
    
  # Multi-GPU training settings
  sync_bn: true  # Sync batch norm stats across GPUs
  find_unused_parameters: true

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: True
